server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  #############################新增网关配置###########################
  cloud:
    gateway:
      routes:
        - id: payment_get_route     # 路由的唯一ID,配合业务命名不重复即可
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:   # 断言
            - Path=/payment/get/**  # 路径断言，路径匹配测进行路由
        - id: payment_lb_route
            #uri: http://127.0.0.1:8002
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/payment/$\{segment}

eureka:
  instance:
    hostname: 127.0.0.1
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka

